### ISSUE TITLE
Can't download merge.idx.stats.pdf file

### ISSUE THREAD

**Issue by mt831** [ICBI/viGEN#3]
Hi,
Does the merge.idx.stats.pdf file have a control access? It seems I couldn't download this file successfully.

Thanks

**Comment by kb472** [comment]
Hello ! Thank you for informing us about this . I have edited the link now to the correct location. You should be able to access it [here]( https://drive.google.com/open?id=0B3-883ME4sP3U0VYUFZUdDdsZkU).  Please contact us if you have any other questions. 

Please remember to cite our work:  Bhuvaneshwar et al. 'viGEN: An Open Source Pipeline for the Detection and Quantification of Viral RNA in Human Tumors', Frontiers in Microbiology (2018). https://www.ncbi.nlm.nih.gov/pubmed/29922260
