### ISSUE TITLE
Missing functionFlagstatBam in viral.pipeline_public_final.sh

### ISSUE THREAD

**Issue by venuraherath** [ICBI/viGEN#4]
Hi  @krithikab472 

functionFlagstatBam is missing in the file. 
Can you update the file with missing items?
Thank you

**Comment by Krithika-Bhuvan** [comment]
My apologies for the delayed response. I seem to have missed this notification !
You can use this code below. Please let us know if you need more information. 

#Function definition.
`functionFlagstatBam() {
	echo "Start - Get flagstat bam file" >> $LOG
	$SAMTOOLS_SOFTWARE"samtools" flagstat $O_FOLDER$FOLDER/$FOLDER".kallisto.sorted.bam" > $O_FOLDER$FOLDER/$FOLDER".flagstat.kallisto.bam.txt"	
	echo "End - Get flagstat bam file" >> $LOG
}`

**Comment by venuraherath** [comment]
Thank you!
