### ISSUE TITLE
RSEM Vs Bowtie 2

### ISSUE THREAD

**Issue by doctorasgr** [ICBI/viGEN#6]
Hi,
Thank you for this great idea with this pipeline. I was trying to run this pipeline on galaxy but I couldn't find the RSEM anywhere. Therefore, I am thinking to try bowtie 2 in the first step to align to the human reference genome and the get the un-aligned reading and run bowtie 2 again to align them to the merged viral reference genome. Do you think that this is going to work or should I definitely use the RSEM on the first step?
Another one question. When you say `viral copy= Number of mapped reads * Read length/ Genome Length` what do you define as read length and what as genome length?
Thanks in advance for your response.

Thanos

**Comment by Krithika-Bhuvan** [comment]
Hello ! Yes you can try with bowtie2 or kallisto as long as you are able to get the un-aligned output files. 
```read length``` is based on the length of the reads in the sequencing platform your data was profiled on. It could be 50, or 75, or 100 etc , it depends on the  sequencing platform of your data.
Unlike the human reference genome where we are dealing with only one genome, the virus fasta reference file we used contains many species. So the ```genome length``` refers to the length of the genome for each viral species.
